// long-running solve messages
export default [
  "Hang in there!",
  "Let go like a bird flies, not fighting the wind but gliding on it",
  "Stay patient and trust the journey.",
  "Everything is coming together…",
  "Solitaire is a journey, not a destination.",
  "For things to reveal themselves to us, we need to be ready to abandon our views about them.",
  "Patience is bitter, but its fruit is sweet.",
  "Strive for progress, not perfection.",
  "I wish only to be alive and to experience this living to the fullest.",
  "This too shall pass.",
  "Life is available only in the present moment.",
  "Patience is the companion of wisdom.",
  "The mountains are calling and I must go.",
  "Give time time.",
  "If you find a path with no obstacles, it probably doesn't lead anywhere",
  "A smooth sea never made a good sailor.",
  "To be upset over what you don’t have is to waste what you do have.",
  "The ultimate freedom lies in being able to wait patiently for a good thing.",
  "If it isn't good, let it die. If it doesn't die, make it good.",
  "A watched pot never boils without applying heat.",
  "Stick with the winners.",
  "I immerse myself in the experience of living without having to evaluate or understand it.",
  "Why fit in when you were born to stand out?",
  "Don't let yesterday take up too much of today.",
  "The least I owe the mountains is a body.",
  "Getting so close!",
  "Many people think excitement is happiness. But when you are excited you are not peaceful.",
  "Misery is optional.",
  "Mistakes are proof that you're trying.",
  "Life would be so much easier if we only had the source code.",
  "A computer once beat me at chess, but it was no match for me at kickboxing.",
  "Patience is not simply the ability to wait, it's how we behave while we're waiting.",
  "We must let go of the life we have planned so as to accept the one that is waiting for us.",
  "Somewhere, something incredible is waiting to be known.",
  "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
  "My actions are my only true belongings.",
  "The way to have enough time is to never be in a hurry.",
  "The more you know, the less you think you know.",
  "Patience is also a form of action.",
];
